### ISSUE TITLE
[bug] unable to upload files to SFTP server

### ISSUE THREAD

**Issue by maverick-dev-55** [mickael-kerjean/filestash#392] opened 2021-04-27 23:18 UTC
I was trying to sftp into my Minecraft server and upload some plugins and when I drag the files to the "DRAG HERE TO UPLOAD" box it just shows up and says __```Uncaught TypeError: Cannot read property 'fullPath' of null```__, I am using falixnodes to host my server if someone wants to try to reproduce this bug

**Comment by Coder-Tavi** [comment] 2021-04-28 16:20
I can confirm that this issue occurs on a Chromebook as well. I'm using a SkySilk Node.JS Basic VPS

**Comment by Coder-Tavi** [comment] 2021-04-28 16:29
I can confirm that this issue occurs on a Chromebook as well. I'm using a SkySilk Node.JS Basic VPS
![image](https://user-images.githubusercontent.com/66774833/116439245-32c46780-a804-11eb-9b0a-3cdc3cf9a511.png)

**Comment by maverick-dev-55** [comment] 2021-04-30 14:49
it may be only Chromebook, i am using Chromebook as well

**Comment by mickael-kerjean** [comment] 2022-01-21 02:37
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process

**Closed by mickael-kerjean** 2022-01-21 02:37 UTC

**Comment by Coder-Tavi** [comment] 2022-01-21 06:18
Been a long time and have since turned that Chromebook off. Don't need support but I think a decent amount of people would benefit from a fix.
