### ISSUE TITLE
Latest version icons missing

### ISSUE THREAD

**Issue by airbillion** [mickael-kerjean/filestash#126] opened 2019-01-15 16:29 UTC
Hello,

I just installed Filestash via docker.  Everything is working correctly, however the icons are missing everywhere:
![image](https://user-images.githubusercontent.com/11315828/51194230-a272ea80-18b8-11e9-8c86-ec6eaaf7f15e.png)

Is this an issue with the latest release or something else?
If I access it by IP locally the icons are missing too...

Any help would be appreciated.

Thanks!

**Comment by mickael-kerjean** [comment] 2019-01-17 07:08
That's interesting, your CLI is saying the favicon is loading fine. Can you try some other things and send the very same screenshots:
1. `curl -L -vvv -X GET http://192.168.1.190:8334/assets/icons/folder.svg`
2. try to navigate in your browser at: `http://192.168.1.190:8334/assets/icons/folder.svg` and `http://192.168.1.190:8334/favicon.ico`

**Comment by airbillion** [comment] 2019-01-17 16:50
1.
![image](https://user-images.githubusercontent.com/11315828/51334470-daf7fd00-1a4d-11e9-8a12-1001eb8b559b.png)
![image](https://user-images.githubusercontent.com/11315828/51334502-ecd9a000-1a4d-11e9-9907-5a9c5170cfbb.png)

2. Each command downloads the file...

I have deleted the container and image a few times, but still have the issue with th eicons not showing...

I also tried host & bridge networking in docker, but that did not help either...

**Comment by mickael-kerjean** [comment] 2019-01-18 00:52
Got it, the problem originate from a wrong value in the Content-Type HTTP header. Essentially when you download a SVG, the response come with a Content-Type header of "image/svg" where what it should send is "image/svg+xml". Because of this, the browser doesn't understand the server is trying to send an SVG image.


- what I suspect is wrong is this file `/app/data/config/mime.json` needs to be update to the latest version; the HTTP Content-Type header value is coming from the mime.json which on the latest version contains [the correct value](https://github.com/mickael-kerjean/filestash/blob/master/config/mime.json#L124). A possible source of the problem is you did persist your mime.json somewhere on the host such as it didn't change during the upgrade and you're still using the [old mime.json version](https://github.com/mickael-kerjean/filestash/blame/master/config/mime.json#L124)
- The fix: If what I suspect is correct, you should be able to get it all working by pulling the new version of the mime.json file that you can find [here](https://raw.githubusercontent.com/mickael-kerjean/filestash/master/config/mime.json)

**Comment by airbillion** [comment] 2019-01-18 15:45
Hello,

That was it!

![image](https://user-images.githubusercontent.com/11315828/51396961-2d005780-1b0e-11e9-8f60-326cadaea144.png)

I replaced the old mime.json with the new one and everything is back to normal!

Thank you!!

**Comment by airbillion** [comment] 2019-01-18 15:49
One last quick question...

Is there a way to select multiple files/folders?

CTRL + multiple files/folders does not work...

Thanks again!!

**Comment by mickael-kerjean** [comment] 2019-01-20 11:38
> Is there a way to select multiple files/folders? 

It is one of the things that's in a todo list for a later release as I'm not sure which approach would be the best from an end user experience perspective. Essentially, there's 2 idea battling in my head:
1. make it work in the same way all the native file manager works: with some sort of a square that select whatever is within the square:
  - Pro: nothing new, nothing to learn, it's the expected behaviour people expect on a desktop
  - Cons: the approach won't work on touch based devices 
2. make it work from a mouseover to a file icon that morph into a clickable checkbox that control the selection state:
  - Pro: it can work on every platform, desktop or touch based device
  - Cons: the native file manager doesn't work that way

Do you have some better idea or preferences?

**Comment by airbillion** [comment] 2019-01-21 15:03
Hello,

Option 2 seems like the best method to me if you can implement it...

I use Filestash on my phone and it would be great to have it be compatable with it and touchscreen laptops/tablets...

However, option 1, woudl work too and can be implemented faster...

**Comment by mickael-kerjean** [comment] 2019-01-22 02:55
I'm closing the issue as the original issue is solved. 

> best method to me if you can implement it...

It's definitely in my todo list but not in the short term one. However:
- pull request are welcome, this will definitely be merged
- you can make it more of a priority by financially supporting the project either via [Patreon](https://patreon.com/mickaelk) or the [website](https://www.filestash.app/pricing)

**Closed by mickael-kerjean** 2019-01-22 02:55 UTC
