### ISSUE TITLE
/files doesn't load (loader is spinning forever)

### ISSUE THREAD

**Issue by pbuyle** [mickael-kerjean/filestash#148] opened 2019-03-22 01:00 UTC
I've a strange issue trying out Filestash. It works great in Chrome or in empty Firefox (65.0.1, Ubuntu 18.10) profile. But not in my regular Firefox profile, even after clearing the cache, cookies, etc. Authentication (against an SFTP server) works. But once redirected to `/files` the loader spin forever. The content of the root folder does not load.

It looks like a client issue since I can browser the file without issue in another browser or using a different profile. I checked with the developer tools, nothing is logged in the console and all network requests get the expect responses.

**Comment by mickael-kerjean** [comment] 2019-03-22 14:35
Thank you for the report. I'm not sure what's the problem at this stage, can you provide more information?
1. which version of filestash are you using? You can find it from `http://filestash.example.com/about`
2. Did you make an upgrade recently?
3. What's happening around your network? See my screenshot 
![image](https://user-images.githubusercontent.com/13233076/54829829-62424500-4d0b-11e9-8ecd-db8a6b476bc3.png)
The interesting bit comes from `/api/files/ls?path=xxxxxxx` where you should see a JSON document that list all the folder that will be drawn by the app. What do you see?

**Comment by pbuyle** [comment] 2019-03-23 14:07
I'm using the `machines/filestash:latest` Docker image (sha256:cfe6ed981f863c4378be0639b2fe12601c00f7046e952d0e20193fba49cb5c38, Created | 2019-03-20 12:49:08) and it is a brand new installation.
Versions is v0.4.20190320 (Rd4OcZ)
- backend_backblaze.so (KSd4cG)
- backend_ldap.so (ngkczd)
- backend_dav.so (6dvTsc)
- security_scanner.so (ncgecb)
- image.so (bZcocV)
- config.json (Gdcbbb)

All network requests seem to be doing fine, see this screenshot. I've a single folder at the root and it is listed in the JSON response. I compared the network requests done in a empty Firefox profile (where everything works) and they appears to be exactly the same with the same response (same order, same response's sizes). 
![network-screenshot](https://framapic.org/vRT3vKDlKZbL/DVlLETHrPGPJ.png)
Assets seems to be loaded fine too, see this screenshot.
![debugger-screenshot](https://framapic.org/fFQ1imyDHxSF/V6bMubn3TtRF.png)

**Comment by mickael-kerjean** [comment] 2019-03-25 01:59
Considering  the issue starts to appear with your profile but everything is working fine without it, I can only assume there's something in your profile that trigger the issue.

Also, the symptoms you're experiencing reminds me of another case a user did setup a man in the middle that was injecting third party script into filestash (Cloudflare in user case) but I guess a plugin in your firefox could also do the same either by injecting things that conflict with the application and crashes it or a plugin that would disable some features filestash needs to work properly

To find the root cause of this, I guess you can try to either:
- disable all your plugins to see if the bug is triggered by one of them. If you find which one, let me know, it would be good to have some sort of error message here to make things more obvious
- send me a sample of such a profile so that I can attempt to create reproduction and find/fix the underlying issue

**Comment by pbuyle** [comment] 2019-03-25 13:19
Yes, it is obvious, something in my profile trigger the issue. I suspected an extensions, but I already tried disabling them (and clearing all the cache, stored data, cookies, etc.). The screenshot I posted were made with all extensions disabled. The Debugger tab shows that no additional script have been injected into the page (if an extension does inject scripts, they are visible with a `moz-extensions://<uuid>` path).

I'll try to produce a profile triggering the issue that I can share with you.

Thanks.

**Comment by pbuyle** [comment] 2019-03-26 02:06
I'm sorry I failed to build a working shareable profile with the issue. I was able to isolate it to the `storage` folder in my profile. Deleting the folder solve the issue. But restoring it from a backup break the profile (once restored, nothing loads in the browser). I messed it up and didn't keep a backup of the whole folder profile, so I'm not unable to reproduce the issue now.

**Comment by mickael-kerjean** [comment] 2019-04-15 05:17
I'm closing as I don't see any way forward at this stage. We'll reopen if we have some steps to reproduce this error

**Closed by mickael-kerjean** 2019-04-15 05:17 UTC
