### ISSUE TITLE
[Feature Request] Add onedrive support

### ISSUE THREAD

**Issue by NavePnow** [mickael-kerjean/filestash#199] opened 2019-09-16 01:59 UTC
The fliestash will be more perfect with supporting onedrive.

**Comment by mickael-kerjean** [comment] 2019-09-27 17:37
Can you send a pull request for it? Personally, I have neither a need and willingness to make it work on my free time.

**Comment by mickael-kerjean** [comment] 2019-11-07 07:17
This is a duplicate of https://github.com/mickael-kerjean/filestash/issues/199 
I'm closing this one. Pull request are welcome to make it happen

**Closed by mickael-kerjean** 2019-11-07 07:17 UTC
Labels: help wanted
