### ISSUE TITLE
too much caching? can't browse file on two git repos

### ISSUE THREAD

**Issue by oz123** [mickael-kerjean/filestash#185] opened 2019-07-24 14:44 UTC
I have configured two git sources:

```
https://example.org/oz123/foo.git
https://example.org/oz123/bar.git
```

Now, I can login to `foo`, files are shown properly. I log out, and then I login to `bar`. The files which are shown are the files from `foo`.

This happens with direct access or with nginx-revese-proxy.

**Comment by mickael-kerjean** [comment] 2019-07-25 01:20
I can't reproduce this, it all works fine from my end. Can you send a reproduction from the official demo: https://demo.filestash.app ?

**Comment by oz123** [comment] 2019-07-25 05:45
1. Run filestash with docker-compose.
2. Use the following nginx setup:

```
server {
    listen         80;
    server_name    filestash.example.org;
    return         301 https://$server_name$request_uri;
   
    location /.well-known/acme-challenge {
        default_type "text/plain";
        root /var/www/.letsencrypt;
    }
}

server {
    listen 443 ssl;
    server_name example.org;
    expires 24h;

    ssl_certificate /etc/letsencrypt/live/filestash.example.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/filestash.example.org/privkey.pem;
    ssl_dhparam /etc/letsencrypt/live/filestash.example.org/dh4096.pem;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
    ssl_ecdh_curve secp384r1;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header     Host $host:$server_port;
        proxy_set_header     X-Real-IP $remote_addr;
        proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header     X-Forwarded-Proto $scheme;
        proxy_set_header     Origin '';

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        proxy_pass           http://127.0.0.1:8334;
        #proxy_read_timeout   86400;
    }
    
    location /.well-known/acme-challenge {
      default_type "text/plain";
      root /var/www/.letsencrypt;
    }
}
```

Add some connections:
```
   "connections": [
        {
            "label": "DOCs",
            "repo": "https://git.example.org/oznt/docs.git",
            "type": "git"
        },
        {
            "label": "Photos",
            "repo": "https://git.example.org/oznt/photos.git",
            "type": "git"
        },
        {
            "label": "TODOs",
            "repo": "https://git.example.org/oznt/todo.git",
            "type": "git"
        },
    ]
```

Thanks for the quick response!

**Comment by mickael-kerjean** [comment] 2019-08-19 07:28
It works very well from my end: 
![screenshot_20190819_172610](https://user-images.githubusercontent.com/13233076/63246661-87c97f80-c2a6-11e9-9401-8c894a63588e.png)

The example you provide from the git.example.org domain don't point anywhere

**Comment by oz123** [comment] 2019-08-19 09:56
The problem isn't adding the sources. The problem is browsing files from two sources.
You screenshot is showing how to add two sources. Can you list files from filestash_latex and tmp1 in the same browsing session?

**Comment by mickael-kerjean** [comment] 2019-08-19 10:52
I'm not sure what you mean, the intended use with multiple git repo would be like this: https://archive.kerjean.me/public/2019/github-2019-08-19_20.44.02

**Comment by mickael-kerjean** [comment] 2019-11-07 07:06
It looks like this issue is dead. I'm closing, feel free to comment back and we'll reopen

**Closed by mickael-kerjean** 2019-11-07 07:06 UTC
