### ISSUE TITLE
[support] Docker behing nginx proxy manager

### ISSUE THREAD

**Issue by skollrc** [mickael-kerjean/filestash#492] opened 2022-07-10 09:42 UTC
Hi everyone, 

First of all, thanks for your great job!

I would like to use filetash in a docker behind nginx proxy manager. Curruntly it does not work. Is there any env variable or something else to allow reverse proxy?

King regards

**Comment by DmitryZakharov** [comment] 2022-09-10 11:32
Could somebody please shine some light  on how to put filestash behind reverse proxy ? 
I need it to work with https://<my-domain>/filestash
if i run it  it always redirects to https://<my-domain>/admin/setup and that jsut simply does not work.

**Comment by mickael-kerjean** [comment] 2022-09-15 22:47
This is covered in the [documentation](https://www.filestash.app/docs/install-and-upgrade/#optional-using-a-reverse-proxy). Filestash listens on port 8334 (a good way to remember is it stands for beer).
I'm closing as this ticket doesn't follow the issue template we've setup. If you want support, the place to go isn't github but IRC #filestash on libera.chat

**Closed by mickael-kerjean** 2022-09-15 22:47 UTC

**Comment by DmitryZakharov** [comment] 2022-09-16 06:54
> This is covered in the [documentation](https://www.filestash.app/docs/install-and-upgrade/#optional-using-a-reverse-proxy). Filestash listens on port 8334 (a good way to remember is it stands for beer). I'm closing as this ticket doesn't follow the issue template we've setup. If you want support, the place to go isn't github but IRC #filestash on libera.chat

Sorry @mickael-kerjean . But the documentation for revers proxy does not help. And have been tried, that is why i posted my comment. What documentation describes only works if you don't run filestash under subpath http://\<host\>/filestash it only works with http://\<host\>/
There must be a configuration on the application level to set baseURL, so that when filestash redirect it includes the baseURL.
Should i file a new ticket , to follow the guide lines or you will reopen the current ticket ?

**Comment by johnmmcgee** [comment] 2023-11-24 14:00
> This is covered in the [documentation](https://www.filestash.app/docs/install-and-upgrade/#optional-using-a-reverse-proxy). Filestash listens on port 8334 (a good way to remember is it stands for beer). I'm closing as this ticket doesn't follow the issue template we've setup. If you want support, the place to go isn't github but IRC #filestash on libera.chat

This documentation no longer appears to exist.

**Comment by ThomasKat** [comment] 2023-12-18 10:42
> This is covered in the [documentation](https://www.filestash.app/docs/install-and-upgrade/#optional-using-a-reverse-proxy). Filestash listens on port 8334 (a good way to remember is it stands for beer). I'm closing as this ticket doesn't follow the issue template we've setup. If you want support, the place to go isn't github but IRC #filestash on libera.chat

Dear @mickael-kerjean, I second @johnmmcgee here, there is no documentation for reverse proxies. I am completely stuck with this Chrome error that seems caused by a missing reverse proxy (traefik) setting in my case
```
Refused to execute script from 'https://filestash.domain.com/web-apps/apps/api/documents/api.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by mickael-kerjean** [comment] 2023-12-18 12:55
The reverse proxy isn't a part of Filestash, there used to be a section in the documentation but I recently got rid of it as it was creating more issues with people asking to support their favorite software, config issues outside the scope of what was in the documentation, etc.... Ultimatly I've spent tons of hours helping people debugging things totally outside the control of Filestash and that didn't help the project one bit.

if you need help set things up and are using Filestash in an enterprise context, getting your company a support contract and we will jump on  a call to get an optimal solution that work best for you and it will help the project a ton as I have a family to feed and can't be doing support on my free time.

**Comment by johnmmcgee** [comment] 2023-12-18 15:16
So removing documentation for those of us that can figure it out is the solution and you expect normal foss home users to pay for a support contract to gain access to this documentation?  Good luck.  I’ll be searching for another project to use and help contribute to.

**Comment by ThomasKat** [comment] 2023-12-18 17:36
Here's an old version of the documentation, @johnmmcgee. I'm not sure it's helping me though 😉🙈 

## Optional: Using a reverse proxy
Using a reverse proxy isn’t mandatory but it is quite useful when you have multiple services installed on your server and can’t dedicate ports 80 and 443 to one specific application.

A sample configuration for Nginx:
```shell
# change the env variable to what you want to use
export FILESTASH_DOMAIN=demo.filestash.app
openssl dhparam -out /etc/letsencrypt/live/$FILESTASH_DOMAIN/dh2048.pem -outform PEM -2 2048

cat > /etc/nginx/sites-available/filestash.conf <<EOF
server {
    listen         80;
    server_name    $FILESTASH_DOMAIN;
    return         301 https://\$server_name\$request_uri;
}
server {
    listen 443 ssl;
    server_name $FILESTASH_DOMAIN;
    expires \$expires;

    ssl on;
    ssl_certificate /etc/letsencrypt/live/$FILESTASH_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$FILESTASH_DOMAIN/privkey.pem;
    ssl_dhparam /etc/letsencrypt/live/$FILESTASH_DOMAIN/dh2048.pem;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
    ssl_ecdh_curve secp384r1;

    # file upload limit
    client_max_body_size 1024M;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header     Host \$host:\$server_port;
        proxy_set_header     X-Real-IP \$remote_addr;
        proxy_set_header     X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header     X-Forwarded-Proto \$scheme;
        proxy_set_header     Origin '';

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        proxy_pass           http://127.0.0.1:8334;
        proxy_read_timeout   86400;
    }
}
EOF

ln -s /etc/nginx/sites-available/filestash.conf /etc/nginx/sites-enabled/filestash.conf
nginx -t && service nginx restart
```

Note: Resist the temptation of using gzip or other caching mechanisms at reverse proxy level, you would waste valuable CPU cycles adding latency and increasing bandwith usage, creating issues with cache invalidation. Filestash is already doing its best at compile time, optimising performance at a level no reverse proxy could ever compete with by using a few lines of configuration and no deep knowledge of the underlying service.

**Comment by mickael-kerjean** [comment] 2023-12-19 09:52
> and you expect normal foss home users

I am not expecting anything from anyone, it's the other way around, I publish a software in the open with the goal it might be usefull for other people. If you think you are entitled to support, I invite you to read this brilliant article made by Rich Hicky, one of my greatest influence in the world of software who wrote this [piece about oss](https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9) in a much better way than what I could explain with my own words.

> to pay for a support contract to gain access to this documentation? Good luck

No, as mention before this specific part of the documentation has cause a lot of lost time on my side and you have to understand that managing an OSS project on the size of Filestash is a massively time intensive job. To summarise it all I have a job that pay my bills and spend another 40 hours a week on Filestash even though the rate per hour I get working on this is much lower than what I would get working in my local mc donald by flipping burgers.

> I’ll be searching for another project to use and help contribute to.

Good luck. FYI by the time I put up my kid to sleep, I would love to spend time with my wife watching movies but instead of doing I spend all my free time working on this, pretty much every day from 20h to 2am. The objective of Filestash is quite optimistic, it's aiming to be a better software than the web client of Dropbox / Google Drive and One drive and I can't say the software is build by a large community when more than 99% of the code is made by myself, hopefully one day that will change but it's not there yet.

With the lack of resources to help build the future of Filestash, I made the decision to prioritise some things over others, in this case rebuilding the frontend is my first priority and to be able to deliver I am trying to reduce the amount of "distraction" as doing everything in the same time is the best way to do nothing at all in the long run.

This is the reason I got rid of this bit in the documentation, it was a massive time loss and I got to realise there's no way you can keep it and not to have people asking other questions about this to do all sort of things that are outside the scope of Filestash. Maybe one day I will expend the documentation part to cover all the different options but as of today the priority is in making the software better.

**Comment by ThomasKat** [comment] 2023-12-19 10:03
Thanks for all your efforts for this really, really great and ambitious project, dear @mickael-kerjean! ❤️💪
