### ISSUE TITLE
[Feature Request] Docker image for Linux/aarch64

### ISSUE THREAD

**Issue by fkromer** [mickael-kerjean/filestash#260] opened 2020-05-13 12:04 UTC
Docker images are provided for [OS/ARCH Linux/amd64](https://hub.docker.com/r/machines/filestash/tags?page=1) only. Would be great if you could provide the docker image for the `aarch64` architecture as well. This would allow to run filestash on machines like the RaspberryPi as well.

To add builds with Travis CI this project could be used as reference: https://github.com/koalaman/aarch64-builder . If you are working on Windows or Mac the blog post [Building Multi-Arch Images for Arm and x86 with Docker Desktop](https://www.docker.com/blog/multi-arch-images/) could be helpful. If you are working on Linux refer to [Getting started with Docker for Arm on Linux](https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/) instead.

**Comment by mickael-kerjean** [comment] 2020-05-14 14:12
That's a duplicate of #233. As I wrote earlier, there's 2 options:
- somebody who is backing the project need that feature and I would use that contribution to pay for an ARM server to be used for the build
- someone make it work from their end and contribute back on the documentation. There's a space on the documentation for Alternative Installation methods and I invite anyone to contribute to it

**Closed by mickael-kerjean** 2020-05-14 14:12 UTC

**Comment by amilino** [comment] 2020-05-21 09:36
Thank you for all work so far, I find your application simple, nice looking and very fast. But some crucial things like sorting that is super strange, paste via Ctrl+v in edit file window and playing of videos that are not working, made me decide to leave the projects.

**Comment by mickael-kerjean** [comment] 2020-05-22 02:13
@amilino: the default key binding for the text editor is emacs and CTRL+v isn't the shortcut you'd expect using emacs. This can be changed from the admin console to have keybinding that are more user friendly.
Also the video is being used by many people already without problem, I haven't had the time to investigate that much on your specific problem on my free time. Also the project is open source, a PR would have been awesome

**Comment by schklom** [comment] 2022-06-15 20:55
@mickael-kerjean FYI, GitHub Actions can build and publish Docker image for you on most platforms (e.g. DockerHub) and most architectures (e.g. ARM), and even test if the image works correctly.
I personally use them to mirror repos that do not offer ARM images and auto-build-publish images (when the Dockerfile doesn't need to be reworked for ARM).
You need to go to the Actions tab, and create a new action.

Action code to auto-build: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
Action code to auto-test: https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md

Note that you can export results of certain commands (e.g. check that the log file contains a sentence) and condition tasks on these results (https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs).
